### ISSUE TITLE
invoice service | create error

### ISSUE THREAD

**Issue by mshahat** [retgits/flogo-components#1]
Hi, 

facing this error while creating invoiceservice flogo app , hints please ? 

```
➜  ~ mshahat go version
go version go1.10 darwin/amd64
➜  ~ mshahat dep version
dep:
 version     : v0.4.1
 build date  : 2018-01-27
 git hash    : 37d9ea0
 go version  : go1.9.3
 go compiler : gc
 platform    : darwin/amd64
➜  ~ mshahat echo $GOPATH
/Users/mshahat/go
➜  ~ mshahat flogo create -f invoiceservice.json invoiceservice
Creating initial project structure, this might take a few seconds ... 
all dirs contained build errors
FATAL: command "create" failed: exit status 1
```

Many thanks,

**Comment by retgits** [comment]
Hi Mohamed, 

`dep` makes use of a bunch of files to be able to create the correct project structure. In order to populate those files Flogo traverses the JSON file and looks for the references to populate the `imports.go`. If you're using `ref` anywhere else, for example as a part of your JSON message (like in this example), Flogo will assume you need to import that URL too (so this is a bug in Flogo).

To fix this, you can follow this workaround:

* Open `invoiceservice/src/invoiceservice/imports.go`
* Remove the line `_ "{{$activity[combine_5].result}}"`
* Save the file
* Run `flogo ensure` from the root of your project

**Comment by retgits** [comment]
Just to add, I've created https://github.com/TIBCOSoftware/flogo/issues/177 to make sure this is tracked in Project Flogo as well
