### ISSUE TITLE
Communicty extension links are broken

### ISSUE THREAD

**Issue by rkiesi** [retgits/flogo-components#19]
Hi Community!
I'm following the Flogo Enterprise training and have a problem for integrating community components as described.
The link for Uploading components like https://github.com/retgits/flogo-components/activity/randomstring or https://github.com/retgits/flogo-components/activity/writetofile are broken. Either browser nor Flogo Enterprise Builder can access the repo to get the components. Perhaps something has changed on Github since the artefacts were last build?
Can you please double check and let me know what the right reference URI for those extensions are?

Thanks a lot!

**Comment by retgits** [comment]
Hi @rkiesi I unfortunately don't have access to the Flogo Enterprise training so I'm not able to help you with that. I'd recommend asking TIBCO support for help there.

**Comment by rkiesi** [comment]
The point is just the links are not correct anymore. -> The material is referencing http://github.com/retgits/flogo-components/activity/writetofile which is not available on Github anymore (http 404). If I download the whole repo as ZIP, extract the subdirectory for one of the activities, create a new zip archive out of this and import the activity via archive instead of the direct github URI it works.
So the links used are not correct anymore. Also, the links within the activity / module description is wrong. I think thats the root cause of the import problem. I already have tried to import via the current repo structure as well with not luck -> https://github.com/retgits/flogo-components/**tree/master/**activity/writetofile
If I understood it correctly, the file "activity.json" is the description. Here the "ref" property uses the broken link to. My guess was, that's the issue the importer is failing on.
Could you please verify this? I don't think Tibco support will be of help here.

**Comment by retgits** [comment]
> The material is referencing http://github.com/retgits/flogo-components/activity/writetofile

Which material is that are you referring to? I'd love to help you out, but I don't have access to Flogo Enterprise or the Flogo Enterprise training so I can't check.

> Also, the links within the activity / module description is wrong. I think thats the root cause of the import problem. Here the "ref" property uses the broken link to. My guess was, that's the issue the importer is failing on.

The `ref` field (like `github.com/retgits/flogo-components/activity/writetofile`) is a Go import path to let the Flogo engine know which go module it needs to download in order to make it work. The Go language specification follows a specific path structure so that's why you see the 404 error (there's no associated web page, Go itself adds the required pieces to the path to download the code). I just verified that `go get github.com/retgits/flogo-components/activity/writetofile` works as expected.

> Could you please verify this? I don't think Tibco support will be of help here.

The Go code seems to work, so there could be changes in how Flogo Enterprise imports activities that are causing this behavior but unfortunately I'm not able to help as I don't have access to any of that material

**Comment by rkiesi** [comment]
Thanks! The §material" is a training available at Tibco Academy _TIBCO Flogo Enterprise - Foundation_, chapter 4. One of the lab exercises show how to import community provided extensions to Flogo Enterprise (docker container running locally - not Tibco Cloud Integration).
I have just tried to import the "writetofile" into Flogo community. Also running as docker container on my dev system. Here it works if I point to the repo link I see in the browser -> https://github.com/retgits/flogo-components/tree/master/activity/writetofile (the new parts are "../tree/master/..".
Seems you are right. There might be more differences between community and enterprise edition in the meantime. That's a bit sad.

Thanks anyway! I'll try engaging support!
